name: easy_forms
description: A new Flutter package project.
version: 0.0.1
author: Alban LECUIVRE
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter